# ================================================================
# Zsh Configuration
# ================================================================

# ---- Options & History ----
setopt appendhistory
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'  # case-insensitive tab completion
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# ---- Environment Variables ----
export EDITOR="nvim"
alias vim="nvim"
alias vi="nvim"
export PATH="$HOME/.local/bin:$PATH"
export FLYCTL_INSTALL="$HOME/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"

# ---- Plugin Loading ----
source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# ---- Tool Initialization ----
source <(fzf --zsh)
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"

# ---- Aliases ----
# ls
alias ls='lsd'
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'
# modern CLI replacements
alias cat='bat --paging=never'
alias find='fd'
alias du='dust'
alias lg='lazygit'
alias rm='rm -v'
# system fixes
alias usbfix='sudo bash ~/dotfiles/scripts/usb-reset.sh'  # revive the 2 dead USB ports + Bluetooth

# ---- Keybindings ----
bindkey '^H' backward-kill-word   # Ctrl+Backspace = delete word backward
bindkey '^Z' undo                 # Ctrl+Z = undo in shell line editor

# ---- AGS Terminal Colors ----
# Applies the colorscheme generated by AGS/Waybar on every shell start
if test -f ~/.cache/ags/user/generated/terminal/sequences.txt; then
    cat ~/.cache/ags/user/generated/terminal/sequences.txt
fi

# ---- Startup ----
pokemon-colorscripts --no-title -s -r | fastfetch -c $HOME/.config/fastfetch/config-pokemon.jsonc --logo-type file-raw --logo-height 10 --logo-width 5 --logo -

# ---- Conda ----
# >>> conda initialize >>>
__conda_setup="$('/home/anonymous/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/anonymous/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/anonymous/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/anonymous/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# ---- Other Tools ----
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"
